### ISSUE TITLE
This is awesome!!! Keep it going!!!

### ISSUE THREAD

**Issue by thebarty** [davidyaha/meteor-collection2-migrations#1]
Hi David,
thanks a lot for this package. It is such a great idea and exactly what I was looking for.
Right now I am making a switch from django to meteor.

Are you aware of djangos migration system? It is really really perfectly designed and you could use it as an inspiration. (https://docs.djangoproject.com/en/1.8/topics/migrations/). Have a look at this video to see how it works. https://www.youtube.com/watch?v=fWRYLVMHREk

There are basically 2 command-line commands to call during development in django:
1) makemigrations-command to generate the migrations. Most of the stuff it does automatically, but if it has questions to the developer it will ask: "Hey, did you rename field 'name' to 'surename'? And you as the developer can say 'yes/no'.
2) migrate-command: It runs the generated migrations for you.

I suggest to go for the "field rename" functions next as it really happens a lot during development that you find a better name for a field?

Keep up the good work
Mike

**Comment by davidyaha** [comment]
Hi Mike,

Thanks for the awesome feedback! 
I have been thinking about this idea as well and I am not sure if it is the right way to do the migrations inside of meteor. The meteor platform excels with plugins that do all of the work behind the scenes for you. I think that if I could find a way to efficiently track renaming of fields it will be pretty awesome to have this package migrate the database by it's own without being have to ask the user. 

That being said, I will introduce a way to call each migration step by its own and also a way to review what was done to the current db. 
Also, right now this migration package only cover the Mongo database with the collection2 package.
I am currently working on a way to module the package so that it will be able to migrate sql based databases and also use the schema's provided by the astronomy package.

Tell me if this seems to you as a good enough solution. If not, please feel free to tell me why and I will probably make the way you suggested as another milestone in the roadmap.

Thanks again,
David

**Comment by thebarty** [comment]
Hi David,

2 more thoughts from my point of view:

**1) To me this auto-update stuff is really scary**. It feels like I am totally loosing control and I am scared of using your package on my "real" project.

I would much prefer the django-workflow:
  1) Develop and change your models (schemas)
  2) After you changed a model you manually call makemigrations (it will generate the sql files)
  3) I can then have a look at what was done and run the migrations with the "migrate" command.

**2) 2 different environment: Development and Production**: Always consider that there needs to be a way to apple the current migrations of the development-db to the production-db when I deploy. So there needs to be a command for this (in django you would transfer files to production server and run "migrate").

Keep up the good work!

**Comment by davidyaha** [comment]
Hi Mike,

Sorry for not getting back to you until now.. I have taken your requests (and some other similar requests) into consideration :). In the last couple of days I've started working on a new sub-package (https://github.com/davidyaha/meteor-simple-schema-versioning) that will handle the simple schema versioning and will let you write your schemas as base schema and delta schemas. The package will then recognise the delta between versions and will give you back the update selector and modifier for you to decide what to do with.
After completing that package, I will try to use it for this package that will probably be auto-migrations package and maybe another package to give the semi-automatic work flow as you've suggested.

All that aside, we do have some deployment issues to resolve as well. Just to give you an idea - In a multi server architecture, only one server should be marked as migration server and after figuring this out, we should also try and resolve issues about down time that right now the servers will suffer from, if you want to keep your data reliable.

Thanks for the feedback, it is very helpful!
David

**Comment by davidyaha** [comment]
Hello Mike,

Just wanted to follow up on my previous comment to let you know that I've co-written a package that is based on top of my simple-schema-versioning and I feel it answers your previous requests.

Please take a look here: https://atmospherejs.com/bookmd/schema-migrations
If you like it, make sure to star the github repos: 
- https://github.com/bookmd/schema-migrations/
- https://github.com/davidyaha/meteor-simple-schema-versioning

So we would know that this is the right direction to go on.

Thanks again,
David
